export const mockAssignments = [
  {
    assignmentId: "A001",
    employeeId: "1001",
    lastName: "山田",
    firstName: "太郎",
    facility: "本園",
    occupation: "保育士",
    grade: "G01",
    period: "2024年度前期",
    status: "進行中",
    evaluator: "佐藤花子",
    updatedAt: "2025-06-01",
  },
  {
    assignmentId: "A002",
    employeeId: "1002",
    lastName: "佐藤",
    firstName: "花子",
    facility: "分園",
    occupation: "看護師",
    grade: "G02",
    period: "2024年度前期",
    status: "未着手",
    evaluator: "山田太郎",
    updatedAt: "2025-06-02",
  },
  {
    assignmentId: "A003",
    employeeId: "1003",
    lastName: "鈴木",
    firstName: "一郎",
    facility: "本園",
    occupation: "調理師",
    grade: "G01",
    period: "2024年度前期",
    status: "完了",
    evaluator: "田中美咲",
    updatedAt: "2025-06-03",
  },
];