export const mockAssignments = [
  {
    assignmentId: "A001",
    employeeId: "1001",
    lastName: "山田",
    firstName: "太郎",
    facility: "本園",
    occupation: "保育士",
    grade: "G01",
    period: "2024年度前期",
    status: "2次考課中",
    workingGuidelinesPrimaryEvaluatorId: "1002",
    workingGuidelinesPrimaryEvaluatorName: "佐藤 花子",
    workingGuidelinesSecondaryEvaluatorId: "1003",
    workingGuidelinesSecondaryEvaluatorName: "鈴木 一郎",
    workingGuidelinesFinalEvaluatorId: "1004",
    workingGuidelinesFinalEvaluatorName: "田中 次郎",
    performanceEvaluationPrimaryEvaluatorId: "1002",
    performanceEvaluationPrimaryEvaluatorName: "佐藤 はなこ",
    performanceEvaluationSecondaryEvaluatorId: "1003",
    performanceEvaluationSecondaryEvaluatorName: "鈴木 一郎",
    performanceEvaluationFinalEvaluatorId: "1004",
    performanceEvaluationFinalEvaluatorName: "田中 次郎",
    updatedAt: "2025-06-01",
  },
  {
    assignmentId: "A002",
    employeeId: "1002",
    lastName: "佐藤",
    firstName: "花子",
    facility: "分園",
    occupation: "看護師",
    grade: "G02",
    period: "2024年度前期",
    status: "3次考課中",
    workingGuidelinesPrimaryEvaluatorId: "1002",
    workingGuidelinesPrimaryEvaluatorName: "佐藤 花子",
    workingGuidelinesSecondaryEvaluatorId: "1003",
    workingGuidelinesSecondaryEvaluatorName: "鈴木 一郎",
    workingGuidelinesFinalEvaluatorId: "1004",
    workingGuidelinesFinalEvaluatorName: "田中 次郎",
    performanceEvaluationPrimaryEvaluatorId: "1002",
    performanceEvaluationPrimaryEvaluatorName: "佐藤 花子",
    performanceEvaluationSecondaryEvaluatorId: "1003",
    performanceEvaluationSecondaryEvaluatorName: "鈴木 一郎",
    performanceEvaluationFinalEvaluatorId: "1004",
    performanceEvaluationFinalEvaluatorName: "田中 次郎",
    updatedAt: "2025-06-02",
  },
  {
    assignmentId: "A003",
    employeeId: "1003",
    lastName: "鈴木",
    firstName: "一郎",
    facility: "本園",
    occupation: "調理師",
    grade: "G01",
    period: "2024年度前期",
    status: "完了",
    workingGuidelinesPrimaryEvaluatorId: "1002",
    workingGuidelinesPrimaryEvaluatorName: "佐藤 花子",
    workingGuidelinesSecondaryEvaluatorId: "1003",
    workingGuidelinesSecondaryEvaluatorName: "鈴木 一郎",
    workingGuidelinesFinalEvaluatorId: "1004",
    workingGuidelinesFinalEvaluatorName: "田中 次郎",
    performanceEvaluationPrimaryEvaluatorId: "1002",
    performanceEvaluationPrimaryEvaluatorName: "佐藤 花子",
    performanceEvaluationSecondaryEvaluatorId: "1003",
    performanceEvaluationSecondaryEvaluatorName: "鈴木 一郎",
    performanceEvaluationFinalEvaluatorId: "1004",
    performanceEvaluationFinalEvaluatorName: "田中 次郎",
    updatedAt: "2025-06-03",
  },
  {
    assignmentId: "A004",
    employeeId: "1004",
    lastName: "田中",
    firstName: "次郎",
    facility: "分園",
    occupation: "保育士",
    grade: "G03",
    period: "2024年度前期",
    status: "未開始",
    workingGuidelinesPrimaryEvaluatorId: "1005",
    workingGuidelinesPrimaryEvaluatorName: "高橋 三郎",
    workingGuidelinesSecondaryEvaluatorId: "1006",
    workingGuidelinesSecondaryEvaluatorName: "田中 次郎",
    workingGuidelinesFinalEvaluatorId: "1007",
    workingGuidelinesFinalEvaluatorName: "鈴木 一郎",
    performanceEvaluationPrimaryEvaluatorId: "1005",
    performanceEvaluationPrimaryEvaluatorName: "高橋 三郎",
    performanceEvaluationSecondaryEvaluatorId: "1006",
    performanceEvaluationSecondaryEvaluatorName: "田中 次郎",
    performanceEvaluationFinalEvaluatorId: "1007",
    performanceEvaluationFinalEvaluatorName: "鈴木 一郎",
    updatedAt: "2025-06-04",
  },
  {
    assignmentId: "A005",
    employeeId: "1005",
    lastName: "高橋",
    firstName: "三郎",
    facility: "本園",
    occupation: "事務員",
    grade: "G02",
    period: "2024年度前期",
    status: "1次考課中",
    workingGuidelinesPrimaryEvaluatorId: "1005",
    workingGuidelinesPrimaryEvaluatorName: "高橋 三郎",
    workingGuidelinesSecondaryEvaluatorId: "1006",
    workingGuidelinesSecondaryEvaluatorName: "田中 次郎",
    workingGuidelinesFinalEvaluatorId: "1007",
    workingGuidelinesFinalEvaluatorName: "鈴木 一郎",
    performanceEvaluationPrimaryEvaluatorId: "1005",
    performanceEvaluationPrimaryEvaluatorName: "高橋 三郎",
    performanceEvaluationSecondaryEvaluatorId: "1006",
    performanceEvaluationSecondaryEvaluatorName: "田中 次郎",
    performanceEvaluationFinalEvaluatorId: "1007",
    performanceEvaluationFinalEvaluatorName: "鈴木 一郎",
    updatedAt: "2025-06-05",
  },
];