export const mockInterviewData = [
{
  period: "2024年前期",
  facility: "八幡デイ・サービスセンター",
  firstName: "拓真",
  lastName: "池田",
  employeeId: "6034",
  EvaluateeResponses: {
    change: "特になし",
    impact: "チームの生産性向上に貢献",
    teammates: "佐藤さん: 積極的に意見を出してくれるため",
    goal: "次期はリーダーシップを発揮したい",
    satisfaction: "非常に満足",
    userRelation: "良好",
    colleagueRelation: "良好",
    contribution: "高い",
    transfer: "特になし",
    retirement: "特になし",
  },
  interviewEvaluatorId: "6033",
  interviewEvaluatorName: "山田 拓真",
  EvaluatorResponses: {}
},
{
  period: "2023年後期",
  facility: "八幡デイ・サービスセンター",
  firstName: "拓真",
  lastName: "池田",
  employeeId: "6034",
  EvaluateeResponses: {
    change: "特になしです。",
    impact: "チームの生産性向上に貢献",
    teammates: "佐藤さん: 積極的に意見を出してくれるため",
    goal: "次期はリーダーシップを発揮したい",
    satisfaction: "非常に満足",
    userRelation: "良好",
    colleagueRelation: "良好",
    contribution: "高い",
    transfer: "特になし",
    retirement: "特になし",
  },
  interviewEvaluatorId: "6033",
  interviewEvaluatorName: "山田 拓真",
  EvaluatorResponses: {}
},
{
  period: "2023年前期",
  facility: "八幡デイ・サービスセンター",
  firstName: "拓真",
  lastName: "池田",
  employeeId: "6034",
  EvaluateeResponses: {
    change: "特にありません。",
    impact: "チームの生産性向上に貢献",
    teammates: "佐藤さん: 積極的に意見を出してくれるため",
    goal: "次期はリーダーシップを発揮したい",
    satisfaction: "非常に満足",
    userRelation: "良好",
    colleagueRelation: "良好",
    contribution: "高い",
    transfer: "特になし",
    retirement: "特になし",
  },
  interviewEvaluatorId: "6033",
  interviewEvaluatorName: "山田 拓真",
  EvaluatorResponses: {}
},
{
  period: "2024年前期",
  facility: "八幡デイ・サービスセンター",
  firstName: "拓真",
  lastName: "山田",
  employeeId: "6033",
  EvaluateeResponses: {
    change: "特になし",
    impact: "チームの生産性向上に貢献",
    teammates: "田中さん: 積極的に意見を出してくれるため",
    goal: "次期はリーダーシップを発揮したい",
    satisfaction: "非常に満足",
    userRelation: "良好",
    colleagueRelation: "良好",
    contribution: "高い",
    transfer: "特になし",
    retirement: "特になし",
  },
  interviewEvaluatorId: "1003",
  interviewEvaluatorName: "鈴木 一郎",
  EvaluatorResponses: {}
}];
