export const mockAssignments = [
  {
    assignmentId: "A001",
    employeeId: "1001",
    lastName: "山田",
    firstName: "太郎",
    facility: "本園",
    occupation: "保育士",
    grade: "G01",
    period: "2024年度前期",
    status: "2次考課中",
    workGuidelinesPrimaryEvaluatorId: "1002",
    workGuidelinesPrimaryEvaluatorName: "佐藤 花子",
    workGuidelinesSecondaryEvaluatorId: "1003",
    workGuidelinesSecondaryEvaluatorName: "鈴木 一郎",
    workGuidelinesFinalEvaluatorId: "1004",
    workGuidelinesFinalEvaluatorName: "田中 次郎",
    performanceReviewsPrimaryEvaluatorId: "1002",
    performanceReviewsPrimaryEvaluatorName: "佐藤 はなこ",
    performanceReviewsSecondaryEvaluatorId: "1003",
    performanceReviewsSecondaryEvaluatorName: "鈴木 一郎",
    performanceReviewsFinalEvaluatorId: "1004",
    performanceReviewsFinalEvaluatorName: "田中 次郎",
    updatedAt: "2025-06-01",
  },
  {
    assignmentId: "A002",
    employeeId: "1002",
    lastName: "佐藤",
    firstName: "花子",
    facility: "分園",
    occupation: "看護師",
    grade: "G02",
    period: "2024年度前期",
    status: "3次考課中",
    workGuidelinesPrimaryEvaluatorId: "1002",
    workGuidelinesPrimaryEvaluatorName: "佐藤 花子",
    workGuidelinesSecondaryEvaluatorId: "1003",
    workGuidelinesSecondaryEvaluatorName: "鈴木 一郎",
    workGuidelinesFinalEvaluatorId: "1004",
    workGuidelinesFinalEvaluatorName: "田中 次郎",
    performanceReviewsPrimaryEvaluatorId: "1002",
    performanceReviewsPrimaryEvaluatorName: "佐藤 花子",
    performanceReviewsSecondaryEvaluatorId: "1003",
    performanceReviewsSecondaryEvaluatorName: "鈴木 一郎",
    performanceReviewsFinalEvaluatorId: "1004",
    performanceReviewsFinalEvaluatorName: "田中 次郎",
    updatedAt: "2025-06-02",
  },
  {
    assignmentId: "A003",
    employeeId: "1003",
    lastName: "鈴木",
    firstName: "一郎",
    facility: "本園",
    occupation: "調理師",
    grade: "G01",
    period: "2024年度前期",
    status: "完了",
    workGuidelinesPrimaryEvaluatorId: "1002",
    workGuidelinesPrimaryEvaluatorName: "佐藤 花子",
    workGuidelinesSecondaryEvaluatorId: "1003",
    workGuidelinesSecondaryEvaluatorName: "鈴木 一郎",
    workGuidelinesFinalEvaluatorId: "1004",
    workGuidelinesFinalEvaluatorName: "田中 次郎",
    performanceReviewsPrimaryEvaluatorId: "1002",
    performanceReviewsPrimaryEvaluatorName: "佐藤 花子",
    performanceReviewsSecondaryEvaluatorId: "1003",
    performanceReviewsSecondaryEvaluatorName: "鈴木 一郎",
    performanceReviewsFinalEvaluatorId: "1004",
    performanceReviewsFinalEvaluatorName: "田中 次郎",
    updatedAt: "2025-06-03",
  },
  {
    assignmentId: "A004",
    employeeId: "1004",
    lastName: "田中",
    firstName: "次郎",
    facility: "分園",
    occupation: "保育士",
    grade: "G03",
    period: "2024年度前期",
    status: "未開始",
    workGuidelinesPrimaryEvaluatorId: "1005",
    workGuidelinesPrimaryEvaluatorName: "高橋 三郎",
    workGuidelinesSecondaryEvaluatorId: "1006",
    workGuidelinesSecondaryEvaluatorName: "田中 次郎",
    workGuidelinesFinalEvaluatorId: "1007",
    workGuidelinesFinalEvaluatorName: "鈴木 一郎",
    performanceReviewsPrimaryEvaluatorId: "1005",
    performanceReviewsPrimaryEvaluatorName: "高橋 三郎",
    performanceReviewsSecondaryEvaluatorId: "1006",
    performanceReviewsSecondaryEvaluatorName: "田中 次郎",
    performanceReviewsFinalEvaluatorId: "1007",
    performanceReviewsFinalEvaluatorName: "鈴木 一郎",
    updatedAt: "2025-06-04",
  },
  {
    assignmentId: "A005",
    employeeId: "1005",
    lastName: "高橋",
    firstName: "三郎",
    facility: "本園",
    occupation: "事務員",
    grade: "G02",
    period: "2024年度前期",
    status: "1次考課中",
    workGuidelinesPrimaryEvaluatorId: "1005",
    workGuidelinesPrimaryEvaluatorName: "高橋 三郎",
    workGuidelinesSecondaryEvaluatorId: "1006",
    workGuidelinesSecondaryEvaluatorName: "田中 次郎",
    workGuidelinesFinalEvaluatorId: "1007",
    workGuidelinesFinalEvaluatorName: "鈴木 一郎",
    performanceReviewsPrimaryEvaluatorId: "1005",
    performanceReviewsPrimaryEvaluatorName: "高橋 三郎",
    performanceReviewsSecondaryEvaluatorId: "1006",
    performanceReviewsSecondaryEvaluatorName: "田中 次郎",
    performanceReviewsFinalEvaluatorId: "1007",
    performanceReviewsFinalEvaluatorName: "鈴木 一郎",
    updatedAt: "2025-06-05",
  },
];