export const mockInterviewData = [
{
  period: "2024年前期",
  facility: "本部",
  firstName: "太郎",
  lastName: "山田",
  employeeId: "1001",
  EvaluateeResponses: {
    change: "特になし",
    impact: "チームの生産性向上に貢献",
    teammates: "佐藤さん: 積極的に意見を出してくれるため",
    goal: "次期はリーダーシップを発揮したい",
    satisfaction: "非常に満足",
    userRelation: "良好",
    colleagueRelation: "良好",
    contribution: "高い",
    transfer: "特になし",
    retirement: "特になし",
  },
  interviewEvaluatorId: "1002",
  interviewEvaluatorName: "佐藤 花子",
  EvaluatorResponses: {}
},
{
  period: "2024年前期",
  facility: "あおば保育園",
  firstName: "花子",
  lastName: "佐藤",
  employeeId: "1002",
  EvaluateeResponses: {
    change: "特になし",
    impact: "チームの生産性向上に貢献",
    teammates: "田中さん: 積極的に意見を出してくれるため",
    goal: "次期はリーダーシップを発揮したい",
    satisfaction: "非常に満足",
    userRelation: "良好",
    colleagueRelation: "良好",
    contribution: "高い",
    transfer: "特になし",
    retirement: "特になし",
  },
  interviewEvaluatorId: "1003",
  interviewEvaluatorName: "鈴木 一郎",
  EvaluatorResponses: {}
}];
